name: Feature Branch Pipeline

on:

  push:
    branches: [ feature/* ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CF cli
      run: |
        starter-kit/scripts/install-pre-reqs.sh

    - name: Build tasks-api
      run: |
        starter-kit/scripts/build.sh

    - name: Unit Test
      run: |
        starter-kit/scripts/unitTests.sh
