name: Feature Branch Pipeline

on:

  pull_request:
    branches: [ develop ]
  push:
#    paths: [ "starter-kit/**" ]
    branches: [ feature/*, features/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CF cli
      run: |
        starter-kit/scripts/install-pre-reqs.sh
    
    - name: Build tasks-api
      run: |
        starter-kit/scripts/build.sh

    - name: Unit Test
      run: |
        starter-kit/scripts/unitTests.sh

    - name: Package App
      run: |
        starter-kit/scripts/package.sh ${{secrets.CF_SERVICE_ACCOUNT_ID}} ${{secrets.CF_SERVICE_ACCOUNT_PASSWORD}}

    - name: Deploy App from S3
      run: |
        starter-kit/scripts/deployFromS3.sh ${{secrets.CF_SERVICE_ACCOUNT_ID}} ${{secrets.CF_SERVICE_ACCOUNT_PASSWORD}} 

  Codescan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
